spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/billar_v002
    username: nian
    password: 8203
    driver-class-name: org.postgresql.Driver
    hikari.connection-timeout: 20000
    hikari.maximum-pool-size: 5

  jpa:
    properties: 
      hibernate: 
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate: 
      ddl-auto: update
    show-sql: true

logging:
  level: 
    org: 
      hibernate: 
        SQL: DEBUG
        type:
          descriptor:
            sql: 
              BasicBinder: TRACE